# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libroute', [dirname(__file__)])
        except ImportError:
            import _libroute
            return _libroute
        if fp is not None:
            try:
                _mod = imp.load_module('_libroute', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libroute = swig_import_helper()
    del swig_import_helper
else:
    import _libroute
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_doubleArray(*args):
  return _libroute.new_doubleArray(*args)
new_doubleArray = _libroute.new_doubleArray

def delete_doubleArray(*args):
  return _libroute.delete_doubleArray(*args)
delete_doubleArray = _libroute.delete_doubleArray

def doubleArray_getitem(*args):
  return _libroute.doubleArray_getitem(*args)
doubleArray_getitem = _libroute.doubleArray_getitem

def doubleArray_setitem(*args):
  return _libroute.doubleArray_setitem(*args)
doubleArray_setitem = _libroute.doubleArray_setitem

def get_size():
  return _libroute.get_size()
get_size = _libroute.get_size

def get_path(*args):
  return _libroute.get_path(*args)
get_path = _libroute.get_path

cvar = _libroute.cvar

